import { image18 } from "../../assets";
const Data = [
    {
      id: "1",
      title: "Anthony Wade",
      category: "Breakfast",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "2",
      title: "Anthony Wade",
      category: "Breakfast",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: " Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "3",
      title: "Anthony Wade",
      category: "Breakfast",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "4",
      title: "Anthony Wade",
      category: "Lunch",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "5",
      title: "Anthony Wade",
      category: "Lunch",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "6",
      title: "Anthony Wade",
      category: "Lunch",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "7",
      title: "Anthony Wade",
      category: "Dinner",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "8",
      title: "Anthony Wade",
      category: "Dinner",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "9",
      title: "Anthony Wade",
      category: "Dinner",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "10",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "11",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "12",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "13",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "14",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "15",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "16",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "17",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "18",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "19",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "20",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "21",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "22",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "23",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
    {
      id: "24",
      title: "Anthony Wade",
      category: "Snaks",
      sub: "Expert in Digital Marketing",
      img: {image18},
      desc: "Lorem ipsum dolor sit amet ipsum Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.",
    },
  ];
   
  export default Data;